### ISSUE TITLE
Date of birth screen

### ISSUE THREAD

**Issue by M0rtale** [juzjus10/Epic-Account-Creator#1]
I think you forgot the date of birth screen or something?

**Comment by juzjus10** [comment]
Yeah, for some countries the birth screen but not on mine

**Comment by juzjus10** [comment]
just use vpn and change location

**Comment by tcmaps** [comment]
It still shows with VPN (US), maybe determined by Chrome / OS locale too.

**Comment by tcmaps** [comment]
sadly not fixable - ElementNotInteractableError: element not interactable

**Comment by tcmaps** [comment]
@juzjus10 please see my PR for fix of multi-language problem. also expect birthday check fix soon...
