### ISSUE TITLE
unlink 2FA

### ISSUE THREAD

**Issue by tcmaps** [juzjus10/Epic-Account-Creator#12]
as mailosaurus is a trial, it may be wise to disable 2FA after securing the game.

i use this code:

`	  
    await driver.get('https://www.epicgames.com/account/password');
    await driver.wait(until.titleIs('Change Your Password'), 150000);
    await driver.sleep(3000)
    await driver.executeScript('var tutu = document.getElementsByClassName("email-auth"); tutu[0].click();')
    await driver.wait(until.elementLocated(By.className('common-disable-container')), 150000);
    await driver.executeScript('var toto = document.getElementsByClassName("proceed-btn"); toto[0].click();')
	await driver.sleep(1000);

`

**Comment by tcmaps** [comment]
i just don't know where to put it to make it disable-able via setting credentials.unlink2FA to true

**Comment by tcmaps** [comment]
you can also just XHR-POST to `https://www.epicgames.com/account/v2/security/ajaxRemoveTwoFactorAuthMethod` with content `type=email`

**Comment by sd1123** [comment]
Thanks for the code above! I figured it out where to place the code lol. it worked for me. I will try to pull request it

**Comment by csenjoyer1337** [comment]
where to put it? i have already 30 accounts xd what now to unlink them all?

**Comment by sd1123** [comment]
Uhh I dont know how to unlink them automatically but you can unlink the new
ones you can create. I uploaded it to my github account. I changed it.

**Comment by tcmaps** [comment]
it could be done with parts of the script to write a login + unlink one, just parse accounts.txt and loop.

**Comment by Bafmaaan** [comment]
Do you have discord? @tcmaps

**Comment by juzjus10** [comment]
Added in latest commit
