### ISSUE TITLE
How to open that? I'm stupid, sorry

### ISSUE THREAD

**Issue by Sid4mean** [juzjus10/Epic-Account-Creator#15]
How to open that? when i'm trying to use "cmd" that tell me commands not exist

**Comment by Zol1d** [comment]
> How to open that? when i'm trying to use "cmd" that tell me commands not exist

1. Open cmd as an admin.
2. Write `cd C:\Users\-your PC username here-\Desktop\Epic-Account-Creator-master`. 
3. Write `npm install`.
4. Write `node epicgames.js`.

Notes: 
1. For this you have to place it on your desktop.
2. -your PC username here- there you need to write your PC account name.
3. make sure you have chromedriver installed.
4. You need to run `npm install` only the fist time.

**Comment by Sid4mean** [comment]
npm install - Npm is not an internal or external command

**Comment by Sid4mean** [comment]
i know about commands bro, thanks but it don't want to work =(

**Comment by csenjoyer1337** [comment]
You don't have node js installed then
