### ISSUE TITLE
Its not issue with the gen but i want help.

### ISSUE THREAD

**Issue by Bafmaaan** [juzjus10/Epic-Account-Creator#17]
So i want to make bot which will remove 2FA from the account.But idk how to do so the bot will take log in data from txt document and paste them to Username and password

**Comment by juzjus10** [comment]
I'm working on it

**Comment by Bafmaaan** [comment]
> I'm working on it

Nice <3 Cant wait

**Comment by Bafmaaan** [comment]
> I'm working on it

Can i ask when it will be done please?

**Comment by juzjus10** [comment]
I'll try making it later. I already made a code to make the bot take logins from account.txt.

**Comment by Bafmaaan** [comment]
> I'll try making it later. I already made a code to make the bot take logins from account.txt.

I saw that but it dont work for me idk why :/

**Comment by Bafmaaan** [comment]
> I'll try making it later. I already made a code to make the bot take logins from account.txt.

Can you add me on discord please? 3cm fuckboi#9939

**Comment by juzjus10** [comment]
Added in latest commit
