### ISSUE TITLE
Civilisation VI

### ISSUE THREAD

**Issue by bushshrub** [juzjus10/Epic-Account-Creator#18]
The purchase url is: `https://launcher-website-prod07.ol.epicgames.com/purchase?namespace=cd14dcaa4f3443f19f7169a980559c62&showNavigation=true&highlightColor=0078f2&offers=fe74b3dad04846e5a58f62aebd3858b6#/purchase/verify?_k=799uhm`

**Comment by juzjus10** [comment]
Hi I was wondering where'd you found this. Just curious cause I tried opening the network tab and this shows instead  `https://www.epicgames.com/store/purchase?namespace=cd14dcaa4f3443f19f7169a980559c62&showNavigation=true&highlightColor=0078f2&offers=fe74b3dad04846e5a58f62aebd3858b6` Thank you for this btw

EDIT: It doesnt work for now

**Comment by bushshrub** [comment]
Both seem to work for me. I'm just copying the old scheme of the GTA V version and it still brings up the purchase page. You can look in my fork of the repo.
