### ISSUE TITLE
Bot which disable 2FA (download)

### ISSUE THREAD

**Issue by Bafmaaan** [juzjus10/Epic-Account-Creator#21]
[2FA Disabler.zip](https://github.com/juzjus10/Epic-Account-Creator/files/4670862/2FA.Disabler.zip)
Just paste your accounts to : Accounts.txt and civ6_accounts.txt and replace credentials with your credentials.

(Its my first "bot" ever i just copy epic games creator and "rewrite" it to bot which disable 2FA)

**Comment by bushshrub** [comment]
There is no need to disable 2FA. The code can be rewritten such that 2FA is not even enabled in the first place. See my fork of this for more information

**Comment by Bafmaaan** [comment]
> There is no need to disable 2FA. The code can be rewritten such that 2FA is not even enabled in the first place. See my fork of this for more information

When ur free trial run out on mailosaur u need to have disabled 2FA or u cant log in anymore

**Comment by juzjus10** [comment]
Thats why I told people to get a subdomain at the first place. Because even if mailosaur expires they can forward it again to their main email or make another mailosaur account

**Comment by tcmaps** [comment]
2 be fair, there was no clear instruction how to get a subdomain. even i could not find out there...
