### ISSUE TITLE
unlink.js error ChromeDriver 81

### ISSUE THREAD

**Issue by csenjoyer1337** [juzjus10/Epic-Account-Creator#25]
Hello i tried updating, i even put chromedriver 81 in the folder but i still get this
![image](https://user-images.githubusercontent.com/64969067/82888911-414a3500-9f4a-11ea-93ea-18d1cc0a40f4.png)

**Comment by csenjoyer1337** [comment]
i got an idea to install it to vm with older chrome maybe?

**Comment by csenjoyer1337** [comment]
Now, im looped in this
![image](https://user-images.githubusercontent.com/64969067/82891334-d6026200-9f4d-11ea-9c24-0b3b08310f6c.png)

**Comment by bushshrub** [comment]
What version of chrome are you running?

**Comment by csenjoyer1337** [comment]
On PC 83, on vm 81

**Comment by bushshrub** [comment]
Your file containing the accounts you want to unlink is empty

**Comment by bushshrub** [comment]
Use chromedriver 83 on your PC version

**Comment by bushshrub** [comment]
@juzjus10 kindly close the issue please.
