### ISSUE TITLE
Creator wont start 

### ISSUE THREAD

**Issue by plbartek89** [juzjus10/Epic-Account-Creator#28]
Hi , 
cant start the updated version of creator.. 
Have  existing Account.txt file with GTA and CIV6.
Node.js v.12.16.3 LTS installed
After download i extracted the Epic-Account-Creator-master on drive c , run npm install , in config dir
puted all informations like api key server id mailosaur....  
downloaded and placed chromedriver.exe in  C:\Epic-Account-Creator-master 

when i run node borderlands.js
`C:\Epic-Account-Creator-master>node borderlands.js
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'output/borderlands_accounts.txt'
[90m    at Object.openSync (fs.js:458:3)[39m
[90m    at Object.readFileSync (fs.js:360:35)[39m
    at register (C:\Epic-Account-Creator-master\borderlands.js:33:20)
    at Object.<anonymous> (C:\Epic-Account-Creator-master\borderlands.js:29:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:1133:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:977:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:877:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  errno: [33m-4058[39m,
  syscall: [32m'open'[39m,
  code: [32m'ENOENT'[39m,
  path: [32m'output/borderlands_accounts.txt'[39m
}

C:\Epic-Account-Creator-master>`

ok , created borderlands_accounts.txt in output dir 
`C:\Epic-Account-Creator-master>node borderlands.js

DevTools listening on ws://127.0.0.1:54442/devtools/browser/9095d488-3515-470f-83bf-54b1a0f691f1
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[name="usernameOrEmail"]"}
  (Session info: chrome=xxx.xxx.xxx.xxx)
    at Object.throwDecodedError (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\http.js:565:13)
    at Executor.execute (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async thenableWebDriverProxy.execute (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:700:17)
    at async toWireValue (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:139:15)
    at async C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:190:16
    at async forEachKey (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:184:9)
    at async convertKeys (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:189:3)
    at async thenableWebDriverProxy.execute (C:\Epic-Account-Creator-master\node_modules\selenium-webdriver\lib\webdriver.js:698:22) {
  remoteStacktrace: 'Backtrace:\n' +
    '\tOrdinal0 [0x00E09563+2725219]\n' +
    '\tOrdinal0 [0x00D08551+1672529]\n' +
    '\tOrdinal0 [0x00BF0359+525145]\n' +
    '\tOrdinal0 [0x00B89755+104277]\n' +
    '\tOrdinal0 [0x00BA53C0+218048]\n' +
    '\tOrdinal0 [0x00B9AAD0+174800]\n' +
    '\tOrdinal0 [0x00BA3D7C+212348]\n' +
    '\tOrdinal0 [0x00B9A94B+174411]\n' +
    '\tOrdinal0 [0x00B82528+75048]\n' +
    '\tOrdinal0 [0x00B835A0+79264]\n' +
    '\tOrdinal0 [0x00B83539+79161]\n' +
    '\tOrdinal0 [0x00D1D607+1758727]\n' +
    '\tGetHandleVerifier [0x00F26546+1050150]\n' +
    '\tGetHandleVerifier [0x00F26291+1049457]\n' +
    '\tGetHandleVerifier [0x00F310D7+1094071]\n' +
    '\tGetHandleVerifier [0x00F26B46+1051686]\n' +
    '\tOrdinal0 [0x00D15B06+1727238]\n' +
    '\tOrdinal0 [0x00D1EB7B+1764219]\n' +
    '\tOrdinal0 [0x00D1ECE3+1764579]\n' +
    '\tOrdinal0 [0x00D34C05+1854469]\n' +
    '\tBaseThreadInitThunk [0x767F6359+25]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x77417C24+228]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x77417BF4+180]\n'
}
^C
C:\Epic-Account-Creator-master>`
Now is Chrome starting and closing in loop

**Comment by bushshrub** [comment]
@juzjus10 please close this issue. 
OP, read the error message **carefully**

**Comment by plbartek89** [comment]
thx for nothing @xiurobert  
u have to read it CAREFULLY

```
ok , created borderlands_accounts.txt in output dir
`C:\Epic-Account-Creator-master>node borderlands.js

DevTools listening on ws://127.0.0.1:54442/devtools/browser/9095d488-3515-470f-83bf-54b1a0f691f1
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[name="usernameOrEmail"]"}
```

**Comment by bushshrub** [comment]
That means your country isn't supported. Be more polite.

**Comment by plbartek89** [comment]
issue was closed , Im from Germany , also when i connect trough VPN (US )same problem.
`DevTools listening on ws://127.0.0.1:58345/devtools/browser/e113aa9e-98c0-47e6-b768-a6b6fe9cba80
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[name="usernameOrEmail"]"}
  (Session info: chrome=83.0.4103.61)

**Comment by bushshrub** [comment]
Replace `usernameOrEmail` with `email` in [this line](https://github.com/juzjus10/Epic-Account-Creator/blob/master/borderlands.js#L61)

**Comment by plbartek89** [comment]
its not saving  the accs in borderlands_accounts.txt  but it works.

**Comment by bushshrub** [comment]
You need to use credentials.json if you are not running borderlands_new_accounts.js
