### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by csenjoyer1337** [juzjus10/Epic-Account-Creator#4]
Hello, in screen is issue when i run the script
![image](https://user-images.githubusercontent.com/64969067/82441135-c42c4500-9a9d-11ea-9cf5-4b64947f453c.png)
Thank you

**Comment by juzjus10** [comment]
pls download chromedriver and put it inside the folder

**Comment by h4Ck3D0001** [comment]
Had the same error, go to chrome, the 3 dots in the top right, Help, About Chrome and update chrome, should work after that

**Comment by csenjoyer1337** [comment]
Omg, works like a charm now, tysm :D

**Comment by csenjoyer1337** [comment]
Oh its Now blocked even with different ip after changing ip what now :/
