### ISSUE TITLE
Login screen error

### ISSUE THREAD

**Issue by csenjoyer1337** [juzjus10/Epic-Account-Creator#7]
Hello, after you register a few accounts, and change ip, you get this screen that the script cant bypass. Any fix please?
![image](https://user-images.githubusercontent.com/64969067/82492279-3759a980-9ae6-11ea-8628-e9ce8c155ee8.png)

**Comment by Bafmaaan** [comment]
same  for me

**Comment by kolour** [comment]
I found out the issue, try to replace the current code inside the javascript file with this: [fix.txt](https://github.com/juzjus10/Epic-Account-Creator/files/4659343/fix.txt)

**Comment by csenjoyer1337** [comment]
@helvetuca Will try in a moment, Will update

**Comment by tcmaps** [comment]
please note this prompt may or not come depending on geolocation so make it conditional

**Comment by tcmaps** [comment]
my dirty way:

`// weird 'login.with' window
	try
  {
    var butonis = await  driver.findElement(By.className('SocialIcon epic-btn'));
    await  butonis.click();
    await  driver.wait(until.titleIs('Register for an Epic Games account | Epic Games'), 5000);
  }
  catch (e) {
  console.log(e);
  }`

**Comment by csenjoyer1337** [comment]
@helvetuca Thank you man, lol this worked :D

**Comment by csenjoyer1337** [comment]
@tcmaps thank you too man :D
