### ISSUE TITLE
Choose how you would like to sign up error.

### ISSUE THREAD

**Issue by ghost** [juzjus10/Epic-Account-Creator#9]
Hello, I'm writing to you again to point out a recent issue on the epic games register page. Now when you register, it takes you to this screen first (after you've put in the date).
![image](https://user-images.githubusercontent.com/40948231/82498903-bfc45400-9abe-11ea-98ce-8e2b9f1a1ccd.png)

I fixed this by adding:

    await driver.wait(until.elementLocated(By.className('epic-btn')), 5000);
    await driver.findElement(By.className('epic-btn')).click();

Hope you can add this to fix this issue.

**Comment by tcmaps** [comment]
please note the prompt may not come for everyone so check for presence first

**Comment by juzjus10** [comment]
fixed in the latest commit
